$(function () {
	$("#tab").datagrid({
		url:uri+"/user/findAllUser",
		title:"用户列表",
		iconCls:"icon-search",
		columns:[[
					{
						  field:'usernick',
						  title:'用户名',
						  sortable:true,
					},
					{
						  field:'userpwd',
						  title:'密码',
						  sortable:true,
					}
		          ]],
		pagination:true,
		pageSize:2,
		pageList:[2,4,6],
		toolbar:"#usertools",
		layout:['list','sep','first','prev','next','last','links'],
	});
});